name: soluzione1_hackathon_fudeo_flutter
description: Applicazione per l'Hackathon Fudeo per Offertelavoroflutter.it

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=2.19.5 <3.0.0"

dependencies:
    envied: ^0.3.0
    flex_color_scheme: ^7.0.4
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    flutter_riverpod: ^2.3.6
    fluttertoast: ^8.2.1
    freezed_annotation: ^2.2.0
    go_router: ^6.5.8
    google_fonts: ^4.0.4
    http: ^0.13.5
    intl: ^0.17.0
    json_annotation: ^4.8.0
    package_info_plus: ^3.1.1
    qr_flutter: ^4.0.0
    riverpod_annotation: ^2.1.1
    url_launcher: ^6.1.10

dev_dependencies:
    build_runner: ^2.3.3
    envied_generator: ^0.3.0
    flutter_launcher_icons: ^0.13.1
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
    freezed: ^2.3.2
    json_serializable: ^6.6.1
    riverpod_generator: ^2.2.1

flutter:
    generate: true
    uses-material-design: true
