name: offertelavoroflutter_it_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
    sdk: ">=2.18.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    #utilities
    logger: ^1.3.0
    flutter_bloc: ^8.1.2
    equatable: ^2.0.5
    pine: ^1.0.2
    auto_route: ^5.0.4
    provider: ^6.0.5
    http: ^0.13.5
    favicon: ^1.1.1
    cached_network_image: ^3.2.3
    auto_size_text: ^3.0.0
    url_launcher: ^6.1.10
    intl: ^0.17.0
    flutter_share_me: ^1.4.0

    # local storage
    flutter_secure_storage: ^8.0.0
    shared_preferences: ^2.1.0

    #theme selector utilities
    hydrated_bloc: ^9.1.0
    path_provider: ^2.0.14

    #UI/UX
    lucide_icons: ^0.144.0
    animated_text_kit: ^4.2.2
    flutter_spinkit: ^5.1.0
    animations: ^2.0.7
    expandable: ^5.0.1
    webview_flutter: ^4.2.0
    circular_menu: ^2.0.1
    flutter_slidable: ^3.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.3.3
    auto_route_generator: ^5.0.3

flutter:
    generate: true
    uses-material-design: true

    assets:
        - assets/images/
        - assets/images/blog/

    fonts:
        - family: Montserrat
          fonts:
              - asset: assets/fonts/Montserrat-Regular.ttf
              - asset: assets/fonts/Montserrat-Bold.ttf
              - asset: assets/fonts/Montserrat-SemiBold.ttf
              - asset: assets/fonts/Montserrat-ExtraBold.ttf
